version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=chris
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./src/database/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=c.espinoza.code@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

# En caso de migración a otra base de datos en mysql
  # mysql:
  #   image: mysql:8.0.31
  #   environment:
  #     - MYSQL_DATABASE=my_store
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - MYSQL_PORT=3306
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./src/database/mysql_data:/var/lib/mysql

# UI donde se administra la base de datos mysql
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin123
  #     - PMA_HOST=mysql
  #   ports:
  #     - 8080:80

  